import React from "react";
import Navbar from "./Navbar";
import Footer from "./Footer"; 
import backgroundImg from "../images/background5.webp"; 

const PrivacyPolicy = () => {
  return (
    <div
      className="min-h-screen bg-cover bg-center bg-no-repeat"
      style={{ backgroundImage: `url(${backgroundImg})` }}
    >
      <Navbar />

      <div className="flex justify-center py-16 px-4 md:px-0">
        <div className="bg-white bg-opacity-90 rounded-xl shadow-lg mt-10 p-6 md:p-12 max-w-4xl">
          <h1 className="text-2xl md:text-3xl font-bold text-[#12ace5] mb-6">
            Privacy Policy
          </h1>

          <p className="text-gray-800 mb-4">
            <strong>Last updated:</strong> Nov 28, 2025
          </p>

          <p className="text-gray-800 mb-4">
            This Privacy Policy describes Our policies and procedures on the collection, use, and
            disclosure of Your information when You use the Service and tells You about Your privacy
            rights and how the law protects You.
          </p>

          <p className="text-gray-800 mb-4">
            We use Your Personal data to provide and improve the Service. By using the Service, You
            agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <h2 className="text-xl font-semibold text-[#12ace5] mt-6 mb-2">Interpretation and Definitions</h2>

          <h3 className="text-lg font-semibold mt-4 mb-2">Interpretation</h3>
          <p className="text-gray-800 mb-4">
            The words of which the initial letter is capitalized have meanings defined under the
            following conditions. The following definitions shall have the same meaning regardless
            of whether they appear in singular or in plural.
          </p>

          <h3 className="text-lg font-semibold mt-4 mb-2">Definitions</h3>
          <p className="text-gray-800 mb-2">For the purposes of this Privacy Policy:</p>
          <ul className="list-disc list-inside text-gray-800 mb-4">
            <li><strong>Account:</strong> a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate:</strong> an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company:</strong> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Havenn Clinic.</li>
            <li><strong>Cookies:</strong> small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country:</strong> refers to: Delhi, India</li>
            <li><strong>Device:</strong> any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data:</strong> any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service:</strong> refers to the Website.</li>
            <li><strong>Service Provider:</strong> any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong>Usage Data:</strong> data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li>
              <strong>Website:</strong> refers to Havenn Clinic, accessible from{" "}
              <a
                href="https://havenn-dentel-clinic.vercel.app/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-500 hover:underline"
              >
                https://havenn-dentel-clinic.vercel.app/
              </a>
            </li>
            <li><strong>You:</strong> the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.</li>
          </ul>

          <h3 className="text-lg font-semibold mt-4 mb-2">Collecting and Using Your Personal Data</h3>
          <h4 className="text-md font-semibold mt-2 mb-1">Types of Data Collected</h4>
          <p className="text-gray-800 mb-2">Personal Data: While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include:</p>
          <ul className="list-disc list-inside text-gray-800 mb-4">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Usage Data</li>
          </ul>

          <p className="text-gray-800 mb-4">Usage Data is collected automatically when using the Service and may include information such as Your Device’s IP address, browser type, pages visited, time spent on pages, unique device identifiers, and other diagnostic data.</p>

          <h3 className="text-lg font-semibold mt-4 mb-2">Use of Your Personal Data</h3>
          <p className="text-gray-800 mb-4">The Company may use Personal Data to provide and maintain our Service, manage Your Account, contact You, provide news or offers, and for other business purposes such as improving the Service.</p>

          <h3 className="text-lg font-semibold mt-4 mb-2">Disclosure of Your Personal Data</h3>
          <p className="text-gray-800 mb-4">We may share Your personal information with Service Providers, Affiliates, business partners, or when required by law or legal obligations.</p>

          <h3 className="text-lg font-semibold mt-4 mb-2">Security of Your Personal Data</h3>
          <p className="text-gray-800 mb-4">While We strive to use commercially acceptable means to protect Your Personal Data, no method of transmission over the Internet or electronic storage is 100% secure.</p>

          <h3 className="text-lg font-semibold mt-4 mb-2">Children’s Privacy</h3>
          <p className="text-gray-800 mb-4">Our Service does not address anyone under the age of 13. We do not knowingly collect Personal Data from anyone under 13.</p>

          <h3 className="text-lg font-semibold mt-4 mb-2">Changes to this Privacy Policy</h3>
          <p className="text-gray-800 mb-4">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>

          <h3 className="text-lg font-semibold mt-4 mb-2">Contact Us</h3>
          <p className="text-gray-800 mb-4">If you have any questions about this Privacy Policy, you can contact us:</p>
          <ul className="list-disc list-inside text-gray-800 mb-4">
            <li>By email: Havennsmilestudio@gmail.com</li>
            <li>By visiting this page on our website: <a href="https://havenn-dentel-clinic.vercel.app/contactus" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Contact Us</a></li>
            <li>By phone number: +91 9315220865</li>
          </ul>
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
